[package]
name = "translatable_proc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
serde = { version = "1.0.218", features = ["derive"] }
strum = { version = "0.27.1", features = ["derive"] }
syn = { version = "2.0.98", features = ["full"] }
thiserror = "2.0.11"
toml = "0.8.20"
